OCAMLMAKEFILE=../OCamlMakefile

SOURCES=git_types.ml cmd.ml actor.ml commit.ml repo.ml test.ml 
RESULT=git
PACKS=unix lwt lwt.unix pcre
ANNOTATE=yes

.PHONY: all
all: dnc
	@ :

include $(OCAMLMAKEFILE)
